// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func StartScript(functionName string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_StartScript_6d10`,
		Function: `function __templ_StartScript_6d10(functionName){window.start = function() {
			window[functionName]()
		}
}`,
		Call:       templ.SafeScript(`__templ_StartScript_6d10`, functionName),
		CallInline: templ.SafeScriptInline(`__templ_StartScript_6d10`, functionName),
	}
}

var _ = templruntime.GeneratedTemplate
